apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: eks-container
          image: 234934568007.dkr.ecr.eu-central-1.amazonaws.com/ecr_repo
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eks-service
spec:
  selector:
    app: web
  ports:
    - name: eks-image
      nodePort: 31555
      port: 80
        
  type: NodePort  
