---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-version-1
  labels:
    client: eks
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      role: webserver
  template:
    metadata:
      name: web
      labels:
        role: webserver
    spec:
      containers:
      - name: web
        image: 234934568007.dkr.ecr.eu-central-1.amazonaws.com/ecr_repo
        ports:
        - name: http
          containerPort: 8070
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: eks_service
  labels:
    role: webserver
spec:
  type: LoadBalancer
  selector:
    role: webserver
  ports:
    - port: 80  
